In [21]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
import numpy as np
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
with MPRester("AaCuMl5yxEVFLZ8n") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-8584")

    # Dos for material id
    dos = m.get_dos_by_material_id("mp-8584")

    # Bandstructure for material id
    bandstructure = m.get_bandstructure_by_material_id("mp-8584")

b=SpacegroupAnalyzer(structure)
print(structure.sites) 
print(b.get_symmetry_operations())
#a=SymmOp(b.get_symmetry_operations())
#print(a.are_symmetrically_related(4.113,4.133))
    
    

[PeriodicSite: Na (2.9037, 1.7719, 9.9417) [0.5000, 0.5000, 0.5000], PeriodicSite: Se (1.4955, 0.9126, 5.1203) [0.2575, 0.2575, 0.2575], PeriodicSite: Se (4.3119, 2.6312, 14.7630) [0.7425, 0.7425, 0.7425], PeriodicSite: Er (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]]
[Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.], Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.], Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.], Rot:
[[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]
tau
[0. 0. 0.], Rot:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
tau
[0. 0. 0.], Rot:
[[ 0. -1.  0.]
 [ 0.  0. -1.]
 [-1.  0.  0.]]
tau
[0. 0. 0.], Rot:
[[ 0.  0. -1.]
 [ 0. -1.  0.]
 [-1.  0.  0.]]
tau
[0. 0. 0.], Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.], Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.], Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.], Rot:
[[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]
tau
[0. 0. 0.], Rot:
[[1. 0. 0.]
 [0. 0. 1.]
 [0.